### ISSUE TITLE
eNahar - orderlist

### ISSUE THREAD

**Issue by cduech** [pherk/nabu#125]
Notizfeld wird angezeigt, nicht Anlassfeld (heißt aber Anlassfeld) - was in der Liste gut wäre. Beim Notizfeld wiederum wäre es gut, wenn es beim Öffenen zu sehen wäre. 
Beim Bearbeiten einer Anforderung (wenn man nicht direkt terminiert) springt man dann zurück auf die 1. Seite der Liste: wäre besser, wenn man dahin zurückspringt, wo man vorher war.

**Comment by pherk** [comment]
- moved to eNahar
