### ISSUE TITLE
careplan-order- workflow

### ISSUE THREAD

**Issue by cduech** [pherk/nabu#126]
Du bist Da ja dran, schreibe nur mal hin, was mir und anderen aufgefallen ist, vielleicht teils schon erledigt?

Anzeige des Anlassfeldes verwechselt mit Notizfeld
-> Wenn ich eine order erstelle und unter Anlass etwas reinschreibe, sehe ich das in eNahar im Feld / resp. Spalte in der Übersicht - nicht. Dort steht, was ich unter Notiz eintrage. Das ist zumindest verwirrend, weil bisher diese info fürs Terminieren interessant war, und weil 'Notiz' in Nabu sich in 'Anlass' in eNahar in der Übersicht verwandelt bzw. in 'Info', wenn ich die order bearbeite.
-> eigentlich kann man beim terminieren beide infos brauchen, notiz (=formale Hinweise wie nur freitags oder so) und Anlass; aber ich bin auch unsicher, ob das dann überfrachtet ist, oder man der Einfachheit halber beide Felder zusammenlegt?

zu viele careplans nach request import, keine infos in der Liste der careplans
Möglichkeit, alle Aktivitäten in einen careplan zu packen wäre gut
-> oft stehen die careplan alle auf active. Ich muss die dann einzeln öffnen, die activity öffnen, um zu sehen, was da los ist. Bei erledigten activity sehe nicht, was das war. Wie kann ich einen cp auf completed setzen? bzw. die activities aus zwei Plänen in einen zusammenführen?

order zT nicht editierbar
-> sorry, das können wir streichen

**Comment by pherk** [comment]
gehts etwas genauer ;-)
- Anlass/Notiz wo? im CarePlan-XForm ist description hinterlegt, das soll so sein
- zu viele CPs? im Ernst?! die stehen alle auf 'active' sind also editierbar und weiterverwendbar
  Dubletten sind einige entstanden, zumeist sind die Anforderungen aber schon erledigt, also der 
  jeweilige CP eigentlich auf 'completed' setzbar ('bisher keine Automatik' -> review problem)
- Infos gibt es im Update
- viel Aufwand, Nutzen?, wenn CPs completed wären, verschwinden damit auch die Activities
- Order sind generell nur editierbar wenn noch nicht irdendwie (zB via eNahar) bearbeitet
  oder gibt es noch einen anderen bug?

**Comment by pherk** [comment]
eNahar: 
- Anlass/Info updated. Um Standardtext (Amb.Besuch) zu vermeiden, wurde dort alternativ Info eingeblendet. 
- Hauptliste zeigt jetzt beides (Anlass:Info)
- beim Vereinbaren wird ebenfalls Prio und Anlass dargestellt.
CarePlan:
- hat im Edit-Menu wieder Canceln / Beenden-Buttons
- Canceln nur möglich, wenn keine Activitäten
- Beenden ignoriert dagegen offene Activitities

**Comment by pherk** [comment]
- Beenden restricted to CP which activity referenced resources are not 'active'.
