### ISSUE TITLE
Tasks filter not correct

### ISSUE THREAD

**Issue by pherk** [pherk/nabu#14]
## Tasks

1. tickets auf der startseite: neue todo tickets erscheinen nicht in der Liste
2. gesendet und offen: zeigt alle offenen Tickets von allen Erbringern

**Comment by pherk** [comment]
ad 1: das neue Ticket Vauseweh ist erschienen
ad 2: bei mir nicht

lieber cduech@, bitte prüfen und kommentieren

**Comment by cduech** [comment]
ad 1: neues todo ticket, also an mich selbst, mit oder ohne Pat. bezug, ist in der Start-Liste offene Aufgaben nicht zu sehen
ad 2: nabu startseite, 'gesendet und offen' zeigt 156 tickets von allen möglichen an alle möglichen Leute, sowohl als duechtingc als auch als admin

**Comment by pherk** [comment]
ad 1: recipient was empty for self-assigned tasks via ticket xform
ad 2: filter in RESTXQ-API was insufficient for "gesendet&offen" selection
