### ISSUE TITLE
Encounter daylist status filter

### ISSUE THREAD

**Issue by pherk** [pherk/nabu#17]
# Tagesliste

1. default Auswahl zeigt auch die gecancelten; ist das Absicht?
2. Aktualisieren der Liste: wenn ich zB die Fertigen sehen will -&gt; scheint nicht zu gehen, wenn ich alle Termine des Tages anzeige, aber schon für eine Erbringergruppe
3. Sollen wir nicht dieselben Ausdrücke für Status (oben, Filter) und Aktion (unten, Statusänderung) nehmen?

**Comment by cduech** [comment]
Muss ich nochmal testen

**Comment by cduech** [comment]
Ok; Aktualisierungsfehler nicht replizierbar
Status / Aktion: kann man so lassen; was bedeutet 'Fehler', '???'

**Comment by pherk** [comment]
Fehler und ??? kann ich fürs Formular aus dem Select rausnehmen,
sind halt im FHIR-Standard definiert

**Comment by pherk** [comment]
subset status defined
closed
