### ISSUE TITLE
EpisodeOfCare new resource

### ISSUE THREAD

**Issue by pherk** [pherk/nabu#193]
EpisodeOfCare see https://www.hl7.org/fhir/episodeofcare.html 
- can be used to describe the different stages of care for chronic ambulant patients
  e.g. 'Anmelderunde', 'FirstDiagnosticRound' and so on can be imagined
- main points are the possibility to name a care manager ('Fallführer') and a care team
- the context property of RequestGroup, Encounter references to EpisodeOfCare,
  no artificial extension is needed for indicating the 'Neuer Patient' condition

refs #129 

questions:
Should we introduce it? makes life more complicated but also better ;-)
Should we abandon the 'Neuer Patient'-Condition, or not?
- the two resources are similar but semantically different
- my opinion, we should use both and accept the additional complexity
How to manage it? 
- depends heavily on the place and workflow (Nabu CarePlan, new workflow item, supervision app)
- any ideas?

**Comment by pherk** [comment]
script to create for all Patients a EoC
- careManager set to last 'arzt' or 'psych'
- add all other participants to team
- status
    - all patients without order -> 'planned'
    - all patients with last encounter more than two years -> 'finished'
    - all other -> 'active'
- extension for last contact, role
delete the NP-tags

**Comment by cduech** [comment]
may be 3 years for setting EoC on finished

**Comment by pherk** [comment]
EoC
- there must be only one EoC per Patient and managingOrganization with status 'planned' or 'active'
- status 'planned' or 'active without careManager means Patient is 'Neu', because careManager is set with
  first academic Encounter (e.g. 'Arzt', 'Psych')
StatusHistory
- statusHistory records any revision in addtion to the actual status changes
- the first revision is named 'first-contact' and takes the problem description recorded from 'Anmeldung'
- further revision for 'Anmeldebogenrunde' are named simply 'revision' plus text
- logged-in user recorded as extension
- careManager change monitoring???

**Comment by pherk** [comment]
- finished
