### ISSUE TITLE
QR valid input, hints?

### ISSUE THREAD

**Issue by pherk** [pherk/nabu#22]
bei den Maßen sollten wir hinschreiben, welche Einheit mögl. ist.

**Comment by pherk** [comment]
- vorgesehen ist ein definition link (uri) auf eine ElementDefinition resource, die kann so etwas
  -> wirkt flexibel aber aufwendig
- eine simple Lösung wäre ein generierter xf:hint auf den base type (String, Datum, Integer ...)

**Comment by cduech** [comment]
wir brauchen keine flexible Lösung - können das Format ja vorschreiben. cm und kg mit Komma?

**Comment by pherk** [comment]
dann müsste man Incompatibilität zum FHIR-Standard zu lassen :-1:

**Comment by pherk** [comment]
[questionnaire-extensions](https://www.hl7.org/fhir/questionnaire-extensions.html) sind die Lösung

**Comment by pherk** [comment]
- qr-xform.xqm: hint version implemented
- questionnaires not yet edited
