### ISSUE TITLE
QR date input, default today? easyDate?

### ISSUE THREAD

**Issue by pherk** [pherk/nabu#23]
welches Datumsformat? default heute wäre doch gut
- default heute für Testdatum?
- easyDate?

**Comment by cduech** [comment]
ja für Testdatum
ist easyDate das Monatsfeld zum anklicken? Wenn ja, dann ja

**Comment by pherk** [comment]
easyDate() hieße, Feld ist xs:string und wird erst im xs:date umgewandelt
wie im Formular oder eher Server weiß ich noch nicht
ist Aufwand

**Comment by pherk** [comment]
- initialDateTime value="h" sets via model->action->setvalue
  current-datetime()
