### ISSUE TITLE
Nabu update V 0.9 problems

### ISSUE THREAD

**Issue by cduech** [pherk/nabu#245]
nabu

- workflow/conditions-list to wide on the rigth side / not possible to reach buttons

enahar-admin

- new meeting: subscriber list should be deleted
- cloning of meeting incl. subscriber list? eventually as enhancement
- new meeting: event: 'bis' field position
- new meeting: event: cannot save

**Comment by pherk** [comment]
nabu conditions: ICD10 and Orphanet joined in one column

**Comment by pherk** [comment]
- index has to be managed to save dirty schedules

**Comment by pherk** [comment]
- meeting improved
