### ISSUE TITLE
Roadmap und Lose Enden v0.8+

### ISSUE THREAD

**Issue by pherk** [pherk/nabu#26]
# CP/Workflow

- automatic CarePlan für neue Patienten? Ziele, Tags, ArbeitsDx?
- individualisierter Erhebungsbogen?
- status und progress notes ausreichend? e.g. Neo-Nachsorge
- Activity edit? abhängige Resourcen automat. canceln, beenden?
- Encounter cancel - reorder
- Neuer Task für Patienten ausserhalb des CP z.Zt. möglich; Vor- und Nachteile?!?
- wer kreiert und pflegt die PlanDefinitions?
- mehr als nur Order-Sets (Tasks?)

# Demographie

- Zwillinge/Geschwister verlinken
- Soznet Post default
- Multilingualität
- Migrationshintergrund
- ORBIS-PID: Eingabe-Pflicht?, Validierung (mit EisTik-Daten?), NOID

**Comment by cduech** [comment]
Das ist alles komplex.... müssen wir glaube ich diskutieren.

- automatic careplan: einfach ein Arzttermin?. oder besser tag oder beides? Aber wie lange und wie heben wir den Status neu auf? Vorschlag: beim ersten Termin
- Verhältnis tag - careplan?

- individualisierter Erhebungsbogen: wäre gut
- task außerhalb CP, Vorteil: intuitiv, einfach, man muss nicht entscheiden, innerhalb welches CP man schreibt bei mehreren, man kann von der Startseite oder aus der Pat. ansicht direkt schreiben; Nachteil: wo erscheint das in der CP Ansicht (das sollte es)

**Comment by pherk** [comment]
- kein automatischer CP
- activity status not changeable from CP
- indiv. Erhebungsbogen, PlanDefs, Demography moved to new issues
- ticket auch ausserhalb von CP weiter möglich
