### ISSUE TITLE
Tagesliste - reorder

### ISSUE THREAD

**Issue by cduech** [pherk/nabu#31]
Sehr gute Lösung: Pat oder wir, Kommentar, reorder oder nicht!! Aber: Fehlermeldung bei reorder (cannot reorder); funktioniert aber, also nur die Meldung ist falsch

**Comment by pherk** [comment]
- die Meldung ist falsch, beruht aber tatsächlich auf einem Bug ;-)
- return value reopenOrder as item() falsch, weil zwei Werte zurückgegeben werden
  -> 500 server error -> submission-error
