### ISSUE TITLE
Conditions - neue Diagnose und Pat. Gruppe

### ISSUE THREAD

**Issue by cduech** [pherk/nabu#35]
Neu eingegebene Diagnose wird nicht gespeichert!
Pat. Gruppe: Die Auswahl aus der drop list sollte wie bei den Diagnosen in den Freitext kopiert werden. Sonst steht in der Übersichtsliste nichts - was blöd ist.

**Comment by pherk** [comment]
eigene Tests bestätigen:
- die Condition wird nicht nur nicht gespeichert, sondern es verschwinden die gänderten Conditions
merkwürdig, ich muss das zu Hause in Ruhe testen; bin jetzt schon 5x unterbrochen worden.
- das ausgewählte kann in den Freitext; ja , wenn das gewünscht wird ;-)

**Comment by pherk** [comment]
Fehler doch noch gefunden :-)
- compatibility problem (*:axis -> *:code)
  Deswegen 'verschwanden' die Diagnosen mit Category HD, ND usw.
