### ISSUE TITLE
careplans - activity  self-assign

### ISSUE THREAD

**Issue by cduech** [pherk/nabu#40]
enhancement: Neue Tasks an mich selbst erstellen, ohne dass ich mich als Empfänger raussuchen muss?

workflow - bug?: Tasks, die ich auf der Startseite schließe, stehen im Careplan weiterhin als offen

**Comment by pherk** [comment]
- Self-Button hinter select-gruppe?
- bug in new issue transferred

**Comment by cduech** [comment]
Ja, self button ist gut

**Comment by pherk** [comment]
- self button implemented
