### ISSUE TITLE
conditions - review

### ISSUE THREAD

**Issue by cduech** [pherk/nabu#41]
Idee aus dem Team: Diagnosen oder Briefe der Pat. nach Strings durchsuchen, zB bestimmte Diagnosen, um so Pat. Gruppen zu sehen (Rückwärts gewannt interessant, wo noch keine tags sind)

**Comment by pherk** [comment]
- wer will das nutzen? Prototyp-Projekt?
- die Diagnosen sind ohnehin schon extrahiert; Diagnosen-Filter für review?

**Comment by cduech** [comment]
ja, letzteres vielleicht. war eine Idee von Anne Koy, um zB CP Patienten zu finden; wenn man das mit Behandlungsdaten zusäztlich einschränkt zB auf ein Jahr könnte das doch tatsächlich interessant sein

**Comment by pherk** [comment]
- review issue
