### ISSUE TITLE
careplans - activities - Fallführer

### ISSUE THREAD

**Issue by cduech** [pherk/nabu#43]
Idee aus dem Team: in der  activity-list den Namen der Erbringer (sofern vorhanden) oder jedenfalls irgendwie des FaFü zeigen? Das sieht man jetzt nur für den careplan selbst, und da könnte es oft die Verwaltung sein. Weiß noch nicht wie; oder man müsste den careplan Autor verändern?

**Comment by pherk** [comment]
- Erbringer aus Activity dereferenzieren ist machbar, weil die ohnehin geladen werden
- careplan author ist eine andere Frage; author der letzten progress-note??
