### ISSUE TITLE
careplan-activity-order#can't modify

### ISSUE THREAD

**Issue by cduech** [pherk/nabu#47]
Ich weiß nicht, ob ich da auf dem letzten Stand bin: Aber wenn ich das richtig sehe, können wir eine task auf der Startseite modifizieren oder erledigen, aber eine Anforderung? Löschen, ändern? geht aus dem careplan heraus zZ noch nicht - ich glaube ohne das, können wir kein update machen?!

**Comment by pherk** [comment]
deswegen kein Update??

- warum sollte man eine Anforderung aus dem CP ändern/erledigen.
  Aktivitäten sollen eigentlich einfach erledigt werden ;-)
  Order können in eNahar editiert werden, aktuell noch Rückmeldung für CP :-(
  aber siehe meinen Kommentar zu #7 
- wenn der Vorschlag ok ist, wird es implementiert

**Comment by cduech** [comment]
ja, für das löschen wäre ich damit einverstanden wie unter #7; finde ich sehr wichtig: Anforderungen werden von neuen Kollegen teils zahlreich vergeben, und erscheinen dann unterwegs oft überflüssig; zB lösche ich oft Logo Anforderungen, wenn das nicht zentral ist oder nach kurzer RS mit den Logopädinnen

aber das modifizieren ist doch eine Möglichkeit, die wir jetzt schon haben und auch nutzen, um

- eine Zeitvorgabe zu ändern
- einen bestimmten Erbringer einzutragen, wenn uns das unterwegs sinnvoll erscheint
- eine Information zum Termin einzutragen (gut, das können wir jetzt auch über Notizen)
- vor allem: Priorität und Wunsch-Datum zu ändern
- einen Kalender auszuwählen oder zu ändern

**Comment by pherk** [comment]
- Order/Task now editable, if status = ('not-started','in-progress')
- Order action 'scheduled' = Encounter 'planned'
- Task action 'scheduled' = Task 'accepted'
