### ISSUE TITLE
Encounter synopsis splitting in two list (planned,past)

### ISSUE THREAD

**Issue by pherk** [pherk/nabu#60]
- overview quicker
- past encounters limited to 10?
- switch for cancelled encounters with info about reasons

**Comment by pherk** [comment]
- two encounter lists ('planned', 'not-planned')
- length limited at 15
- 'past' encounters with status and history text (not further tested)

question
:    - Cancelled encounters only visible via button? reduces visual strain
     - do we need a button to see all encounters?

**Comment by cduech** [comment]
the questions above: yes and yes

**Comment by pherk** [comment]
- two button solution in production
    - default shows onls planned and tentative encounters
    - 'Letzte 15' includes cancelled 
    - 'Alle Besuche' show only finished
