### ISSUE TITLE
workflow careplan activities

### ISSUE THREAD

**Issue by cduech** [pherk/nabu#64]
als enhancement?: Vernknüpfen vorhandener order oder appointments mit dem careplan, ggf sogar Integration von Careplans?
Irgendeine Standardunterscheidung zw. diagnost. Abklärung und Versorgung/Betreuung bei vorhandener Diagnose?

**Comment by pherk** [comment]
- first idea moved to #65 
- no need for second; should be clear from title, goals and so on
