### ISSUE TITLE
order - old orders connecting to patient/careplan?

### ISSUE THREAD

**Issue by cduech** [pherk/nabu#65]
Fällt mir blöderweise erst jetzt auf - aber wir können bestehende orders (immerhin >3000) nur in eNahar sehen, bearbeiten etc. , nicht aber beim Pat. in Nabu.
Brauchen wir nicht eine Übergangslösung?
Wäre zB nicht folgendes elegant: alle bestehenden Anforderungen werden einem automatisch generierten careplan zugeordnet, der könnte zB currentCareplan heißen oder irgendwie... Wir könnten dann darum bitten, diese Pläne zu modifizieren, zB umbenennen, beenden etc.

**Comment by pherk** [comment]
- effort should be small enough
- new careplan function exists
- addActivity to CP function and migrate wrapper needed

**Comment by pherk** [comment]
- implemented, tested
- not yet in Echtsystem
