### ISSUE TITLE
CarePlan activity workflow

### ISSUE THREAD

**Issue by pherk** [pherk/nabu#7]
Löschen oder Abhaken einer Aktivität im CarePlan bewirkt (noch) nichts an der Aktivität selbst
Vorschläge??

**Comment by cduech** [comment]
Schwierig: müssen wir diskutieren. Man könnte sich vorstellen, dass die Aktivitäten, zb Termin order verwandelt sich in geplant, dann in fertig, auch im careplan sieht und verfolgt; umgekehrt könnte man den eine Anforderung auch vom careplan aus zB löschen, wenn man das unterwegs für überflüssig hält.

**Comment by pherk** [comment]
mein Kompromiss-Vorschlag ist

- Order und Task von CP aus cancel-bar, wenn noch keine "Aktivität" seitens Erbringer
  also nur assigned
  d.h. wenn Order/Task accepted durch Erbringer sind oder schon eine weitere Aktion zB Termin
  vereinbart wurde, sind sie nicht mehr vom CarePlan aus cancel-bar
- der Status der Aktivität müsste dafür im CP 'irgendwie' erkennbar sein
